# Generated by Django 3.2.25 on 2025-11-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20251114_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate_type', models.CharField(choices=[('certificate', 'Certificate'), ('trust_badge', 'Trust Badge')], default='certificate', max_length=20)),
                ('icon_svg', models.TextField(help_text="SVG path element (the 'd' attribute value)")),
                ('icon_color', models.CharField(default='#4abbc1', help_text='Hex color code for icon background', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which certificates are displayed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
